### PR TITLE
Fix to bypass exception when no constructor

### PR DESCRIPTION
**Pull request by kompotkot**
## Changes

If there are no constractor it throws an error:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/project/project_cli.py", line 26, in <module>
    if CONTRACT_FUNCTIONS["constructor"] is None:
KeyError: 'constructor'
```

## How to test these changes?

Tested locally

### CODE REVIEW

**Review by zomglings — APPROVED** [review]
lgtm

**Review by Andrei-Dolgolev — CHANGES_REQUESTED** [review]
You can pin version as well as https://github.com/bugout-dev/engine/blob/e4b1bf9b7ad1c6a327144e88e40420c960356262/api/setup.py#L25 in engine.

**Review by zomglings — APPROVED** [review]
lgtm

**Comment by zomglings** [comment]
@Andrei-Dolgolev : Can you please approve?

**Review by Andrei-Dolgolev — APPROVED** [review]
Looks good

**Pull request merged**
